export const PASSENGER_NAME = 'PASSENGER_NAME';
export const EMAIL = "EMAIL";
export const FLIGHT_NUMBER = "FLIGHT_NUMBER";
export const BAGGAGE_NUMBER = "BAGGAGE_NUMBER";
export const DEPARTURE_AIRPORT = "DEPARTURE_AIRPORT";
export const ARRIVAL_AIRPORT = "ARRIVAL_AIRPORT";
export const ADD_PASSENGER_DETAIL = "ADD_PASSENGER_DETAIL";